remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Tutorial Materials
description: Website for testing jekyll-theme-minimal for use with tutorial materials
show_downloads: true
